platform :ios

pod 'SSToolkit'
pod 'AFNetworking', '>= 0.2.1'
pod 'CocoaLumberjack', '~> 1.2.0'
pod 'Objection', github: 'https://github.com/atomicobject/objection.git'
pod 'JSONKit', '1.1.0'
pod 'HipsterInBerlin'

generate_bridge_support!
